### ISSUE TITLE
Pseudo code API/test API

### ISSUE THREAD

**Issue by rvanooyen** [rvanooyen/Nudge#5]
Test API
empty fetch call 
console.log results

**Comment by benkaan001** [comment]
@rvanooyen I just pushed an array of countries along with country code, which is used by Teleport, and country currency code. 
I also included a drop down function to give visual html representation. Please ignore the `country_dropdown` function in `script2.js` because I did not code that one.

**Comment by benkaan001** [comment]
@rvanooyen updated the countries select dropdown with my own code.
